name: QA check

on:
  workflow_dispatch:
    inputs:
      github_ref:
        required: true
        type: string

jobs:
  qa-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Check QA
        run: npx ./scripts/check-qa.ts --github_ref=${{ github.event.inputs.github_ref }}
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
